[project]
name = "czolg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.11.0.86",
    "pymavlink>=2.4.43",
    "pyserial>=3.5",
]
